services:
  app:
    build: .
    volumes:
      - .:/app
      - ./input:/input
      - ./output:/output
    ports:
      - "8888:8888"
    working_dir: /app
    env_file:
      - .env
    # Optional: direkt main.py starten
    #command: python main.py

