services:
  app:
    build: .
    volumes:
      - ./:/app
      - ./input:/app/input           
      - ./data/chroma:/app/data/chroma
      - ./output:/output
    ports:
      - "8888:8888"
    working_dir: /app
    env_file:
      - .env
    command: python main.py  # ✅ Startet main.py beim Containerstart
    #command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''